src/Entity/Games.php
<?php

namespace App\Entity;

use App\Repository\GamesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GamesRepository::class)]
class Games
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $image_url = null;

    #[ORM\Column(length: 255)]
    private ?string $platform = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $release_date = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $trailer = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(string $image_url): self
    {
        $this->image_url = $image_url;

        return $this;
    }

    public function getPlatform(): ?string
    {
        return $this->platform;
    }

    public function setPlatform(string $platform): self
    {
        $this->platform = $platform;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(?\DateTimeInterface $release_date): self
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTrailer(): ?string
    {
        return $this->trailer;
    }

    public function setTrailer(?string $trailer): self
    {
        $this->trailer = $trailer;

        return $this;
    }
}

src/Controller/GamesController.php
<?php

namespace App\Controller;

use App\Entity\Games;
use App\Entity\UserData;
use DateTime;
use Doctrine\DBAL\Exception;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\{Request, Response, RedirectResponse};
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

class GamesController extends AbstractController
{

    public function showGamesByPlatform(string $platform, ManagerRegistry $doctrine, SessionInterface $session, Request $request): Response
    {
        $formBar = $this->createFormBuilder()
            ->add('search', TextType::class,
                ['row_attr' => ['class' => 'search_bar']])
            ->getForm();
        $formBar->handleRequest($request);
        if($formBar->isSubmitted() && $formBar->isValid()) {
            $data = $formBar->getData();
            return $this->redirectToRoute('app_search', ['string' => $data['search']]);
        }


        $games = $doctrine->getManager()->getRepository(Games::class)->findAllGamesOrderByName($platform);

        /*$repo = $em->getRepository(Games::class);
        $games = $repo->findAllGamesOrderByName($platform);*/
        return $this->render('games/index.html.twig', ['formBar' => $formBar->createView(), 'games' => $games, 'session' => $session]);
    }

    /**
     * @throws Exception
     */
    public function showGameByPlatformAndId(string $id, EntityManagerInterface $em, SessionInterface $session, Request $request): Response
    {
        $formBar = $this->createFormBuilder()
            ->add('search', TextType::class,
                ['row_attr' => ['class' => 'search_bar']])
            ->getForm();
        $formBar->handleRequest($request);
        if($formBar->isSubmitted() && $formBar->isValid()) {
            $data = $formBar->getData();
            return $this->redirectToRoute('app_search', ['string' => $data['search']]);
        }
        $repoTableGame = $em->getRepository(Games::class);
        $repoUserData = $em->getRepository(UserData::class);
        $game = $repoTableGame->findOneBy(['id' => $id]);
        $userHaveGame = $repoUserData->gameIsPossessed($session->get('UserID'),$id);


        return $this->render('games/individualGame.html.twig', ['formBar' => $formBar->createView(), 'haveGame' => $userHaveGame,'game' => $game, 'session' => $session]);
    }

    public function deleteGame(string $platform, string $id, EntityManagerInterface $em, SessionInterface $session): RedirectResponse
    {
        $repoTableData = $em->getRepository(UserData::class);
        $row = $repoTableData ->findOneBy(['id_game' => $id, 'id_user' => $session->get('UserID')]);
        $em->remove($row);
        $em->flush();

        return $this->redirectToRoute('app_one_game', ['id' => $id, 'platform' => $platform]);
    }

    public function addGame(string $platform, string $id, EntityManagerInterface $em, SessionInterface $session): RedirectResponse
    {
        $row = $this->initRow($id, $session->get('UserID'));
        $em->persist($row);
        $em->flush();

        return $this->redirectToRoute('app_one_game', ['id' => $id, 'platform' => $platform]);
    }


    // TOOLS

    private function initRow($id_game, $id_user): UserData
    {
        $res = new UserData();
        $res->setIdGame($id_game);
        $res->setIdUser($id_user);
        $res->setAdded(new DateTime());
        return $res;

    }



}

templates/games/index.html.twig
{% extends 'header.html.twig' %}

{% block head %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset("css/list_game_style.css") }}">
{% endblock %}

{% block body %}
    {{ parent() }}
    {% set array = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', "EOT"] %}
    {% for a in array %}

        {% set arrayGames = ShowAllGamesByLetter(a , games) %}
        {% if isNotEmptyArray(arrayGames) %}
            <div class="in_line_games">
            <p class="letter">{{ a }}</p>
                <div class="container_games">
                    {% for game in arrayGames %}
                         <a href="{{ path('app_one_game', {platform: game.getPlatform(), id: game.getId()}) }}"><img class="{{ getClass(game.getPlatform()) }}" src="{{ game.getImageUrl() }}"/></a>
                    {% endfor %}
                </div>
            </div>
        {% endif %}


    {% endfor%}

    {% for game in games %}
        
    {% endfor %}

{% endblock %}

templates/games/individualGame.html.twig
{% extends 'header.html.twig' %}

{% block head %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset("css/individual_game_style.css") }}">
{% endblock %}

{% block body %}
    {{ parent() }}
    <div class="game">
    <div class="desc">
        <img src="{{ game.imageUrl }}" class="img_game" alt="image du jeu">
        <div class="desc_text">
            <h3>{{ game.name }}</h3>
            <p class="description">{{ game.description }}</p>
            <p>Platforme : {{ game.platform }}</p>
            <p>Date de sortie en france : {{  dateToString(game.releaseDate) }} </p>
            {% if session.get('isConnected') %}
                {% if haveGame %}
                   <img class="plus_minus" src=" {{ asset('img/minus.png') }}" alt="plus" onclick="window.location.href='{{ path('app_delete_game', {platform: game.platform, id: game.id}) }}'"/>

                {% else %}
                    <img class="plus_minus" src=" {{ asset('img/plus.png') }}" alt="minus" onclick="window.location.href='{{ path('app_add_game', {platform: game.platform, id: game.id}) }}'"/>
                {% endif %}
            {% endif %}
        </div>
    </div>

{% endblock %}